services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tbox-microservice:latest
    pull_policy: build
    container_name: tbox-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      # Add any environment variables your service needs
    ports:
      - "3000:3000"
    networks:
      - tbox-network
    # Uncomment if you need to mount volumes
    # volumes:
    #   - ./config:/app/config:ro
    #   - logs:/app/logs

networks:
  tbox-network:
    driver: bridge

# Uncomment if using volumes
# volumes:
#   logs: