services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tbox-microservice:latest
    pull_policy: build
    container_name: tbox-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT:  3030
      SERVICE_NAME: tbox-api
      SERVICE_VERSION: 1.0.0
      JAEGER_ENDPOINT: http://jaeger:4317
      # Add any environment variables your service needs
    ports:
      - "3030:3030"
    networks:
      - tbox-network
    depends_on:
      - jaeger
    # Uncomment if you need to mount volumes
    # volumes:
    #   - ./config:/app/config:ro
    #   - logs:/app/logs

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "5775:5775/udp"     # Zipkin/Thrift compact
      - "6831:6831/udp"     # Thrift compact
      - "6832:6832/udp"     # Thrift binary
      - "5778:5778"         # HTTP config/metrics
      - "16686:16686"       # Jaeger UI
      - "14268:14268"       # HTTP collector
      - "14250:14250"       # gRPC collector
      - "9411:9411"         # Zipkin compatible endpoint
      - "4317:4317"         # OTLP gRPC receiver
      - "4318:4318"         # OTLP HTTP receiver
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - tbox-network

networks:
  tbox-network:
    driver: bridge

# Uncomment if using volumes
# volumes:
#   logs: